# Generated by Django 3.1.5 on 2021-03-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgf', '0002_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
