# Generated by Django 3.1.5 on 2021-03-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgf', '0003_joinrequest_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
