# Generated by Django 3.2 on 2021-04-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgf', '0003_event_eventseat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tag',
            field=models.CharField(choices=[('charity', 'Charity'), ('conference', 'Conference'), ('self-development', 'Self Development')], default='charity', max_length=20),
        ),
    ]
